# 社交链接
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "我的 GitHub"
    url        = "https://github.com/wujiadongCN"

    [social.params]
        icon = "brand-github"
